version: "3.8"
services:

  shepherd:
    image: mazzolino/shepherd:latest
    secrets:
      - shepherd-registries-auth
    environment:
      IMAGE_AUTOCLEAN_LIMIT: 5
      SLEEP_TIME: '1m'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager

secrets:
  shepherd-registries-auth:
    external: true